. $(theRealPath emoji.sh)
. $(theRealPath terminal.sh)
. $(theRealPath terminalCapture.sh)
. $(theRealPath files.sh)
. $(theRealPath daemon.sh)
. $(theRealPath variables.sh)
. $(theRealPath system.sh)
. $(theRealPath misc.sh)
. $(theRealPath build.sh)
. $(theRealPath printDir.sh)
. $(theRealPath db.sh)
. $(theRealPath git.sh)
. $(theRealPath sshgit.sh)
. $(theRealPath log.sh)
. $(theRealPath gemini.sh)
. $(theRealPath evsieve.sh)
. $(theRealPath wireguard.sh)
. $(theRealPath testDirHistory.sh)
. $(theRealPath remote.sh)
. $(theRealPath shed.sh)
. $(theRealPath prompt.sh)
. $(theRealPath tree.sh)
. $(theRealPath user.sh)
. $(theRealPath cad.sh)
. $(theRealPath windowSwitcher.sh)
. $(theRealPath to.sh)
. $(theRealPath deploy.sh)
. $(theRealPath claude.sh)
. $(theRealPath vscode.sh)
. $(theRealPath chrome.sh)
. $(theRealPath keyring.sh)
# extra
if [ -f "$(theRealPath extra/extra.sh 2>/dev/null)" ]; then
  . "$(theRealPath extra/extra.sh 2>/dev/null)"
fi