(return 0 2>/dev/null) || { echo "Script must be sourced"; exit 1; }

# Generate Version.h from git commit count
VERSION=$(git rev-list --count HEAD 2>/dev/null || echo "0")
cat > include/Version.h << EOF
#ifndef VERSION_H
#define VERSION_H

// Auto-generated by build.sh from git commit count
// DO NOT EDIT MANUALLY
#define DAEMON_VERSION ${VERSION}

#endif // VERSION_H
EOF
echo "Version: ${VERSION}"

echo "Stopping services..."

# Stop via systemd (proper way - ensures clean ungrab)
# Stop via systemd (proper way - ensures clean ungrab)
sudo /usr/bin/systemctl stop daemon.service 2>/dev/null || true
# Also kill any orphan processes not managed by systemd
./stop_daemon.sh 2>/dev/null || true
# Give time for ungrab to complete
sleep 0.5

# Ensure socket directory exists with correct permissions
if [ ! -d "/run/automatelinux" ]; then
    echo "Creating /run/automatelinux..."
    sudo /bin/mkdir -p /run/automatelinux
fi
# If running as root (e.g. during install), set to root:root. Otherwise use sudo user or current user.
if [ "$(id -u)" -eq 0 ]; then
    chown root:root /run/automatelinux
else
    sudo /usr/bin/chown $USER:$USER /run/automatelinux
fi

if [ ! -d "build" ]; then
    mkdir -p build
    chmod g+s build
fi
cd build
cmake .. > /dev/null && \
make > /dev/null && \
echo -e "${GREEN}Build complete!${NC}" && \
sudo cp daemon .. && \
sudo chown root:coding ../daemon && \
cd ..

# Install man page
if [ -f "doc/daemon.1" ]; then
    sudo mkdir -p /usr/local/share/man/man1
    sudo cp doc/daemon.1 /usr/local/share/man/man1/daemon.1
    sudo mandb -q 2>/dev/null || true
fi

if [ -z "$SKIP_SERVICE_RESTART" ]; then
    echo "Reloading systemd and starting daemon.service..."
    sudo /usr/bin/systemctl daemon-reload
    sudo /usr/bin/systemctl start daemon.service
fi
