kill $DAEMON_COPROC_PID 2>/dev/null
wait $DAEMON_COPROC_PID 2>/dev/null  
sleep 0.2
coproc DAEMON_COPROC { socat - UNIX-CONNECT:"$AUTOMATE_LINUX_SOCKET_PATH" 2>/dev/null; }
export AUTOMATE_LINUX_DAEMON_FD_IN=${DAEMON_COPROC[1]}
export AUTOMATE_LINUX_DAEMON_FD_OUT=${DAEMON_COPROC[0]}
