. $(theRealPath sendKeys.bash)
. $(theRealPath daemon.bash)
. $(theRealPath build.bash)
. $(theRealPath printDir.bash)
. $(theRealPath prepareBuild.bash)
. $(theRealPath gnome.bash)
. $(theRealPath changeTitle.bash)
. $(theRealPath log.bash)
. $(theRealPath theRealPath.bash)
. $(theRealPath cd.bash)
. $(theRealPath changeDevice.bash)
. $(theRealPath grep.bash)

