deleteFunctions() {
    for f in $(declare -F | awk '{print $3}'); do
        unset -f "$f"
    done
}
deleteFunctions
export AUTOMATE_LINUX_PATH_END=/ #or ''?
export AUTOMATE_LINUX_DIR="/home/yaniv/coding/automateLinux$AUTOMATE_LINUX_PATH_END"
export AUTOMATE_LINUX_BASH_RC_DIR="${AUTOMATE_LINUX_DIR}bashrc$AUTOMATE_LINUX_PATH_END"
export AUTOMATE_LINUX_ENV_FILE="$AUTOMATE_LINUX_BASH_RC_DIR/env.sh"
export AUTOMATE_LINUX_SYMLINK_DIR="$AUTOMATE_LINUX_DIR/symlinks"
export AUTOMATE_LINUX_DIR_HISTORY_DIR="${AUTOMATE_LINUX_BASH_RC_DIR}dirHistory/"
export AUTOMATE_LINUX_DIR_HISTORY_FILE="${AUTOMATE_LINUX_DIR_HISTORY_DIR}dirHistory.sh"
export AUTOMATE_LINUX_DIR_HISTORY_POINTER
export AUTOMATE_LINUX_PROMPT_COMMAND_SCRIPT_FILE="${AUTOMATE_LINUX_BASH_RC_DIR}promptCommand.sh"
export AUTOMATE_LINUX_BASH_RC_LOG_FILE="${AUTOMATE_LINUX_BASH_RC_DIR}bashrcLog.txt"
export AUTOMATE_LINUX_VERBOSE=true
export AUTOMATE_LINUX_DIR_HISTORY_FILE_BASE="${AUTOMATE_LINUX_DIR_HISTORY_FILE%.*}"
export AUTOMATE_LINUX_TTY=$( (tty) | tr "/" "_" )
export AUTOMATE_LINUX_DIR_HISTORY_FILE_TTY=$( echo "$AUTOMATE_LINUX_DIR_HISTORY_FILE_BASE"$AUTOMATE_LINUX_TTY.sh )
export AUTOMATE_LINUX_BINDINGS_DIR="${AUTOMATE_LINUX_BASH_RC_DIR}bindings/"
export AUTOMATE_LINUX_DIR_HISTORY_POINTERS_FILE="${AUTOMATE_LINUX_DIR_HISTORY_DIR}dirHistoryPointers.sh"
export AUTOMATE_LINUX_TRAP_DIR="${AUTOMATE_LINUX_BASH_RC_DIR}trap/"
export AUTOMATE_LINUX_TRAP_DEBUG_FILE="${AUTOMATE_LINUX_TRAP_DIR}trapDebugLog.txt"