alias mk='mkdir'
alias boot='history -a && sudo reboot'
alias pkill='sudo pkill -9'
alias pkillev='sudo pkill -9 evsieve'
alias evsievep='sudo evsieve --input /dev/input/event* --print format=direct'
alias 1restart='restartCorsairKeyBoardLogiMouseService.sh reset'
alias 1stop='stopCorsairKeyBoardLogiMouseService.sh'
alias trr='tr ":" "\n"'
alias sourceb='source ~/.bashrc'
alias lstr='ls --color=always | tr " " "\n"'
alias cls='clear'
alias cd..='cd ..'
alias cdc='cd /home/yaniv/coding/'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias treec='tree -C | less -R'
alias lsc='ls --color=always | less -R'