alias mk='mkdir'
alias boot='history -a && sudo reboot'
alias pkill='sudo pkill -9'
alias pkillev='sudo pkill -9 evsieve'
alias 1restart='restartCorsairKeyBoardLogiMouseService.sh reset'
alias 1stop='stopCorsairKeyBoardLogiMouseService.sh'
alias trr='tr ":" "\n"'
alias sourceb='source ~/.bashrc'
alias cls='clear'
alias cd..='cd ..'
alias cdc='cd "/home/yaniv/coding/automateLinux"'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias treec='tree -C | less -R'
alias lsc='ls --color=always | less -R'
alias ther='theRealPath'
alias sb='source ~/.bashrc'
alias phone='/snap/bin/scrcpy --video-bit-rate 8M --max-size 1920'
alias phoneFullScreen=' adb connect 10.0.0.142:5555 && /snap/bin/scrcpy --video-bit-rate 8M --max-size 1920 --fullscreen'
alias bs='b -source'

