firstTime(){
    local AUTOMATE_LINUX_DAEMON_IN_FILE="${AUTOMATE_LINUX_DATA_DIR}relay_${AUTOMATE_LINUX_TTY_NUMBER}_in"
    local AUTOMATE_LINUX_DAEMON_OUT_FILE="${AUTOMATE_LINUX_DATA_DIR}relay_${AUTOMATE_LINUX_TTY_NUMBER}_out"
    rm -f "$AUTOMATE_LINUX_DAEMON_IN_FILE" "$AUTOMATE_LINUX_DAEMON_OUT_FILE" 2>/dev/null
    mkfifo "$AUTOMATE_LINUX_DAEMON_IN_FILE" "$AUTOMATE_LINUX_DAEMON_OUT_FILE" 2>/dev/null
    (
        stdbuf -o0 -i0 cat "$AUTOMATE_LINUX_DAEMON_IN_FILE" | \
        stdbuf -o0 -i0 nc -U "$AUTOMATE_LINUX_SOCKET_PATH" 2>/dev/null > "$AUTOMATE_LINUX_DAEMON_OUT_FILE"
    ) &
    sleep 0.2
    exec {AUTOMATE_LINUX_DAEMON_IN_FD}>"$AUTOMATE_LINUX_DAEMON_IN_FILE"
    exec {AUTOMATE_LINUX_DAEMON_OUT_FD}<"$AUTOMATE_LINUX_DAEMON_OUT_FILE"
    cmd=$(printf "rm -rf %s 2>/dev/null; kill %s 2>/dev/null" "'$AUTOMATE_LINUX_DAEMON_IN_FILE' '$AUTOMATE_LINUX_DAEMON_OUT_FILE'" $!)
    # export AUTOMATE_LINUX_DAEMON_IN_FD AUTOMATE_LINUX_DAEMON_OUT_FD
    trap "$cmd" HUP
}
firstTime
unset firstTime

# daemon openedTty
