. theRealPathFile
export AUTOMATE_LINUX_DIR="$(theRealPath ../)"
export AUTOMATE_LINUX_TERMINAL_DIR="${AUTOMATE_LINUX_DIR}terminal/"
export AUTOMATE_LINUX_ENV_FILE="${AUTOMATE_LINUX_TERMINAL_DIR}env.sh"
export AUTOMATE_LINUX_SYMLINK_DIR="${AUTOMATE_LINUX_DIR}symlinks"
export AUTOMATE_LINUX_PROMPT_COMMAND_SCRIPT_FILE="${AUTOMATE_LINUX_TERMINAL_DIR}promptCommand.sh"
export AUTOMATE_LINUX_VERBOSE=true
# export AUTOMATE_LINUX_BINDINGS_DIR="${AUTOMATE_LINUX_TERMINAL_DIR}bindings/"
export AUTOMATE_LINUX_DATA_DIR="${AUTOMATE_LINUX_DIR}data/"
# DIR_HISTORY related variables
# export AUTOMATE_LINUX_DIR_HISTORY_DEFAULT_DIR="/home/yaniv/coding/"
# export AUTOMATE_LINUX_DIR_HISTORY_DIR="${AUTOMATE_LINUX_DATA_DIR}dirHistory/"
# export AUTOMATE_LINUX_DIR_HISTORY_FILE_BASE="${AUTOMATE_LINUX_DIR_HISTORY_DIR}dirHistory"
# export AUTOMATE_LINUX_ESCAPED_TTY=$( tty | tr "/" "_" )
# export AUTOMATE_LINUX_DIR_HISTORY_TTY_FILE="${AUTOMATE_LINUX_DIR_HISTORY_FILE_BASE}${AUTOMATE_LINUX_ESCAPED_TTY}.sh" 
# export AUTOMATE_LINUX_DIR_HISTORY_POINTERS_FILE="${AUTOMATE_LINUX_DIR_HISTORY_DIR}dirHistoryPointers.sh"
# export AUTOMATE_LINUX_DIR_HISTORY_TESTS_DIR="${AUTOMATE_LINUX_TERMINAL_DIR}tests/"
export AUTOMATE_LINUX_PRINT_BLOCK_SEPARATOR="------------------------------------------"
export AUTOMATE_LINUX_TERMINAL_FUNCTIONS_DIR="${AUTOMATE_LINUX_TERMINAL_DIR}functions/"
export AUTOMATE_LINUX_TRAP_DIR="${AUTOMATE_LINUX_TERMINAL_DIR}trap/"
export AUTOMATE_LINUX_TRAP_ERR_FILE="${AUTOMATE_LINUX_TRAP_DIR}err.sh"
export AUTOMATE_LINUX_TRAP_ERR_LOG_FILE="${AUTOMATE_LINUX_DATA_DIR}trapErrLog.txt"
export AUTOMATE_LINUX_TRAP_ERR_LOG_FILE_BACKGROUND="${AUTOMATE_LINUX_DATA_DIR}trapErrLogBackground.txt"
export AUTOMATE_LINUX_TRAP_DEBUG_FILE="${AUTOMATE_LINUX_TRAP_DIR}debug.sh"
export AUTOMATE_LINUX_TRAP_GENERATOR_FILE="${AUTOMATE_LINUX_TRAP_DIR}trapGenerator.sh"
export AUTOMATE_LINUX_TRAP_EXIT_FILE="${AUTOMATE_LINUX_TRAP_DIR}exit.sh"
export AUTOMATE_LINUX_TRAP_HUP_FILE="${AUTOMATE_LINUX_TRAP_DIR}hup.sh"
export AUTOMATE_LINUX_SOCKET_PATH="/run/automatelinux/automatelinux-daemon.sock"
export AUTOMATE_LINUX_TTY_NUMBER=$( tty | sed 's/\/dev\/pts\///' )
export AUTOMATE_LINUX_DAEMON_DIR="${AUTOMATE_LINUX_DIR}daemon/"
export AUTOMATE_LINUX_DAEMON_PID=$(${AUTOMATE_LINUX_DAEMON_DIR}getDaemonPID.sh)
if [ ! -d "$AUTOMATE_LINUX_DATA_DIR" ]; then
    mkdir -p "$AUTOMATE_LINUX_DATA_DIR"
fi
echo $AUTOMATE_LINUX_PRINT_BLOCK_SEPARATOR>$AUTOMATE_LINUX_TRAP_ERR_LOG_FILE
echo $AUTOMATE_LINUX_PRINT_BLOCK_SEPARATOR>$AUTOMATE_LINUX_TRAP_ERR_LOG_FILE_BACKGROUND
# export AUTOMATE_LINUX_FD=automateLinuxFDNotSetYet

